@file:Suppress("DuplicatedCode")

val alphabet: Map<Char, List<List<Boolean>>> = mapOf(
    'A' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
    ),
    'B' to listOf(
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, false),
    ),
    'C' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'D' to listOf(
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, false),
    ),
    'E' to listOf(
        listOf(true, true, true, true, true),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, true, true, true, true),
    ),
    'F' to listOf(
        listOf(true, true, true, true, true),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
    ),
    'G' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, false),
        listOf(true, false, false, true, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'H' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
    ),
    'I' to listOf(
        listOf(true, true, true, true, true),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(true, true, true, true, true),
    ),
    'J' to listOf(
        listOf(false, false, false, false, true),
        listOf(false, false, false, false, true),
        listOf(false, false, false, false, true),
        listOf(false, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'K' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, true, false),
        listOf(true, false, true, false, false),
        listOf(true, true, false, false, false),
        listOf(true, false, true, false, false),
        listOf(true, false, false, true, false),
        listOf(true, false, false, false, true),
    ),
    'L' to listOf(
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, true, true, true, true),
    ),
    'M' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, true, false, true, true),
        listOf(true, false, true, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
    ),
    'N' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, true, false, false, true),
        listOf(true, false, true, false, true),
        listOf(true, false, false, true, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
    ),
    'O' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'P' to listOf(
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
    ),
    'Q' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, true, false, true),
        listOf(true, false, false, true, true),
        listOf(false, true, true, true, true),
    ),
    'R' to listOf(
        listOf(true, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, true, true, true, false),
        listOf(true, false, true, false, false),
        listOf(true, false, false, true, false),
        listOf(true, false, false, false, true),
    ),
    'S' to listOf(
        listOf(false, true, true, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, false),
        listOf(false, true, true, true, false),
        listOf(false, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'T' to listOf(
        listOf(true, true, true, true, true),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
    ),
    'U' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, true, true, false),
    ),
    'V' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, false, true, false),
        listOf(false, true, false, true, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
    ),
    'W' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(true, false, true, false, true),
        listOf(true, false, true, false, true),
        listOf(true, true, false, true, true),
        listOf(true, false, false, false, true),
    ),
    'X' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, false, true, false),
        listOf(false, false, true, false, false),
        listOf(false, true, false, true, false),
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
    ),
    'Y' to listOf(
        listOf(true, false, false, false, true),
        listOf(true, false, false, false, true),
        listOf(false, true, false, true, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
        listOf(false, false, true, false, false),
    ),
    'Z' to listOf(
        listOf(true, true, true, true, true),
        listOf(false, false, false, true, false),
        listOf(false, false, true, false, false),
        listOf(false, true, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, false, false, false, false),
        listOf(true, true, true, true, true),
    ),
)